name: Angular

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Node Version
        uses: actions/setup-node@v1

      - name: Angular Build
        working-directory: src/DatingApp-SPA
        run: |
          npm install
          npm run build